# tell which versioin of docker compose to use.
version: "3"

services:
  web: # name of the service
    environment:
      NODE_ENV: docker_development
    ports:
      - "3000:5001"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
